### PR TITLE
Wear & Seed Support

### PR DESCRIPTION
**Pull request by exababy**

### CODE REVIEW

**Comment by Nereziel** [comment]
```
        document.getElementById('wear<br />
<b>Warning</b>:  Undefined variable $defindex in <b>index.php</b> on line <b>52</b><br />
').addEventListener('input', function () {
            document.getElementById('wearValue<br />
<b>Warning</b>:  Undefined variable $defindex in <b>index.php</b> on line <b>53</b><br />
').innerText = this.value;
```

**Comment by crashzk** [comment]
@exababy would an improved wear system be possible? Something like:

image

User puts the wear he wants exactly in the case.

**Comment by shaikhnedab** [comment]
also is it possible to show current wear and seed?

**Comment by crashzk** [comment]
Would it be possible to apply the Wear and Seed change only to the skin we chose?

Example, I changed the AK-47 Case Hardened wear and deed:
image

However, if I take another AK-47 Blue Laminte skin, for example, the seed and wear apply to it too.
image

**Comment by crashzk** [comment]
> To do this, more than one skin number must be entered for the selected weapon and a separate table must be created, this is not something I can do right now.

I understand, without wanting to abuse more, regarding StatTrak and Nametag, would it just be a change in the web interface or do you need modifications to the plugin as well?

**Pull request merged**
