### PR TITLE
Translate `paint_name` to any language

### PR DESCRIPTION
**Pull request by yichen11818**
This project may not need this translation, but I believe it is helpful for Chinese users. i am willing to share it with anyone who might be interested :)
i translated`agents.json`  `gloves.json` `skins.json`

### CODE REVIEW

**Comment by emreires** [comment]
Can you please share the function that was used to retrieve the API data in different languages? I know you only change the "en" to the target language code, but retrieving them in the same structure as in the data folder?

https://github.com/Nereziel/cs2-WeaponPaints/issues/58

**Comment by emreires** [comment]
Man, fr? Are you using the Google Translate to do it? lmao, just use the API, it has the languages...

**Comment by yichen11818** [comment]
> Man, fr? Are you using the Google Translate to do it? lmao, just use the API, it has the languages...

i just see that api. its much better and esaier,lmao.ill update soon

**Comment by yichen11818** [comment]
> Man, fr? Are you using the Google Translate to do it? lmao, just use the API, it has the languages...

now i use that api :)

**Pull request closed without merging**
